### ISSUE TITLE
Using streams with gtensor

### ISSUE THREAD

**Issue by td-mpcdf** [wdmapp/gtensor#138]
It seems to be necessary to somehow make it possible to use the (CUDA) streams with gtensor. In the launch of an explicit  kernel this could be another argument, in the assignment kernels, we should add a function set_stream(streamID) and launch the assignment kernel in this stream. A set_default_stream should set it back.

**Comment by germasch** [comment]
So what is the use case that you're actually thinking about? Passing a stream to `launch` wouldn't be too hard, but it'll also require wrappers for creating / destroying streams, etc -- in a way that's portable to HIP (easy) and Intel, too. And there's the rather complicated sync semantics with respect to other streams and the default stream to keep in mind. A `set_stream` function that essentially sets a default stream for subsequent gtensor kernel invocations also needs some more thinking to ensure thread safety if gtensor is used from within a (host-)threaded environment.

**Comment by bd4** [comment]
FWIW I think I can do SYCL stream emulation, by creating extra queues on demand as new streams are set in the already existing global singleton class, which is currenlty used to emulate library global default device.

I don't know if HIP has a per thread default stream option? Also SYCL definitely does not, so that approach is not portable (although perhaps DPCPP has something with there compatibility tool for translating CUDA?).

I think an argument can be made that what SYCL does, with no global state and having queue objects to encapsulate a device/stream combo, is a better API - if an application wants global state, it can define a global queue. While defining it in the library is convenient, it lacks flexibility and leads to challenges when you have multiple host threads. Currently gtensor has already inherited the global state stuff from CUDA/HIP though, so I'm not sure we want to change - it basically involves passing an extra object (the queue) to every API call, or making it a method on the queue object. I guess I'm not sure if CUDA/HIP support overriding the global device though.... something to think about.

**Comment by bd4** [comment]
Looks like it uses OpenCL to support other accelerators.

**Comment by bd4** [comment]
@carlosenlopez do you know if a global (per process) set_stream would work with the StarPU integration? As an alternative, we could define an assign(lhs, rhs, stream=null) function, so you could just pass the stream from starpu, but loose the nice lhs = rhs syntax.

**Comment by carlosenlopez** [comment]
Here it is the answer of one of the StarPU developers:

> By default, 1 host thread per GPU device is used by the CUDA driver. If 
STARPU_NWORKER_PER_CUDA > 1, this environment variable indicates how many 
host threads are used by the CUDA driver for one GPU device.
>
>Asynchronous data movements involving cudaMemcpy*() functions always explicitly
specify the stream they used for transfers. However, if asynchronous transfers
fail, StarPU falls back to synchronous transfers over the default stream.
>
>In StarPU's source file "src/drivers/cuda/starpu_cublas.c", you can have
a look at the starpu_cublas_init() function, which basically executes a
cublasSetStream() on each worker thread at initialization time. Perhaps
the same approach would be fine for the gtensor library?

**Comment by carlosenlopez** [comment]
You can access the StarPU source code here https://gitlab.inria.fr/starpu/starpu

**Comment by bd4** [comment]
Initial implementation now in main branch, see [test_stream.cxx](tests/test_steam.cxx). Not that for the interoperability use case, you would generally use `gt::stream_view` directly and not use `gt::stream` at all.
