### ISSUE TITLE
linear and index array accessors

### ISSUE THREAD

**Issue by bd4** [wdmapp/gtensor#55]
For the SYCL assign/launch and sum_axis_to reduction routine, linear indexing based on expression shape is used to create N dimensional implementations. This is done using the `index_expression` helper function (currently only works up to 6d), which is hacky. This could also be generally useful elsewhere in gtensor to generalize functions beyond six dimension, and to create specialized routines in application code.

A related operation is access based on an index object, rather than `operator()` style which takes separate arguments. gview.h implements some of these for internal use, for arbitrary dimension. This could be refactored and moved so, for example, all containers support both linear access and sarray index access.

We can look to xtensor for what interface we might want to provide for this:
https://xtensor.readthedocs.io/en/latest/indices.html
https://xtensor.readthedocs.io/en/latest/quickref/basic.html#element-access
https://xtensor.readthedocs.io/en/latest/view.html#flatten-views
https://xtensor.readthedocs.io/en/latest/quickref/basic.html#data-buffer

So one possibility is `operator[]` for index array style access (`a[{0, 7}] == a(0, 7)`), and forcing the use of `a.data()` to get linear indexing. However `a.data()` only works on container types, not general expressions, so it is less powerful for implementing n-dimensional routines. Currently `gcontainer` provides the `data_access` method for this, but again it's limited to container types and container spans only.

Also note that gtensor currently assumes column major (Fortran style) indexing. If we add this functionality, it is another place that will need to be updated if row major and other layouts are added.

**Comment by germasch** [comment]
Fundamentally, I like `a[{0, 7}]`. I don't think it necessarily conflicts with `a[100]` since those can be disambiguated by the arg type, though one may have to be careful that there's no ambiguity with implicit conversions.

For now, I'd only support the sarray index to be of length == `expr_dimension(E)` that it's being passed to, so all it really does is unpack and pass things through to the multi-arg `operator()`.

I'm not sure that linear indexing via something like `a[100]` is desirable to have (in the public interface). I'd say if one wants to have a flattened view, that'd better be supported by something like `ravel` or `flatten`. In terms of a cheap way to iterate over all values, one should probably provide iterators instead of some (seemingly) linear access.

On the data layout, I think it's another issue that will probably require some thought. Fundamentally, gtensor and gtensor_view use an array of strides, so the underlying data can be row-major or column-major or whatever, and access will work. I guess you can make a row-major gtensor right now using `swapaxis`. But I also think it's true that in some select places (other than the initial initialization of the strides) there is an assumption of col-major, ie., some expression stuff may break, and that should be handled properly, though I also think I remember some non-trivial obstacles to that...

**Comment by bd4** [comment]
Closed by #62 and #56. Implements the simplest form, in particular operator[] only supports shape types, not literal arrays. Linear access is handled via the `flatten` view helper.
