### ISSUE TITLE
rename development branch to main

### ISSUE THREAD

**Issue by germasch** [wdmapp/gtensor#81]
I suggest renaming -> `main` -- going with the times --, unless there are any objections.

**Comment by bd4** [comment]
Agreed. github was going to add some tooling to make this seemless, not sure if they have released that yet? It wouldn't be too hard for us to change without that though, we might need to adjust the GENE update.sh, otherwise it's just a few of us with checked out repos that would need to change our config.

**Comment by bd4** [comment]
Looks like support for this on github is pretty mature, I vote we go ahead and make the change: https://github.com/github/renaming

**Comment by germasch** [comment]
Feel free to just do it, looks like it should be pretty seamless. (I've done it on another project a while back, and it didn't cause any trouble, but it was mostly me who was affected in the first place...)

**Comment by germasch** [comment]
I did it, so you'll need to rename your local `master` branch name, and gene's update.sh should be updated, though it'll probably continue to work as-is.

**Comment by bd4** [comment]
Thanks, wasn't hard to rename my fork as well, it prompted me. Closing.
